version: '3'
services:
  app:
    build: ./
    ports:
      - "9071:9071"
      - "8071:8071"
    expose:
      - 9071
      - 8071
    volumes:
      - .:/app
    container_name: spring-boot-skeleton
    image: spring-boot-skeleton